name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm run format:check
          npm run lint
          npm run build
          npm run test:run

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$TAG" >> $GITHUB_OUTPUT
          echo "MAJOR=$(echo $TAG | cut -d. -f1)" >> $GITHUB_OUTPUT
          echo "TAG_NAME=v$TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: git.home.alaghband.com
          username: ${{ secrets.GITEA_USERNAME }}
          password: ${{ secrets.GITEA_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            git.home.alaghband.com/farhad/alexa-photos:latest
            git.home.alaghband.com/farhad/alexa-photos:${{ steps.version.outputs.VERSION }}
            git.home.alaghband.com/farhad/alexa-photos:${{ steps.version.outputs.MAJOR }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Create Release Notes
        id: release_notes
        run: |
          cat << EOF > release_notes.md
          ## Docker Images

          \`\`\`bash
          docker pull git.home.alaghband.com/farhad/alexa-photos:${{ steps.version.outputs.VERSION }}
          \`\`\`

          ### Available tags:
          - \`${{ steps.version.outputs.VERSION }}\` - This specific version
          - \`${{ steps.version.outputs.MAJOR }}\` - Latest in v${{ steps.version.outputs.MAJOR }}.x
          - \`latest\` - Latest stable release

          ### Deployment

          Update your \`docker-compose.yml\`:
          \`\`\`yaml
          services:
            sync:
              image: git.home.alaghband.com/farhad/alexa-photos:${{ steps.version.outputs.VERSION }}
              volumes:
                - ./data:/app/data
              env_file:
                - .env
              restart: unless-stopped
          \`\`\`

          Then pull and restart:
          \`\`\`bash
          docker compose pull
          docker compose up -d
          \`\`\`
          EOF

      - name: Create Gitea Release
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        run: |
          RELEASE_NOTES=$(cat release_notes.md)
          curl -X POST \
            -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/json" \
            "https://git.home.alaghband.com/api/v1/repos/farhad/alexa-photos/releases" \
            -d @- << EOF
          {
            "tag_name": "${{ steps.version.outputs.TAG_NAME }}",
            "name": "Release ${{ steps.version.outputs.VERSION }}",
            "body": $(echo "$RELEASE_NOTES" | jq -Rs .),
            "draft": false,
            "prerelease": false
          }
          EOF
